MDScreenManager:
    id: screenmanager

    MDScreen:
        name: "silog"
        md_bg_color: app.theme_cls.backgroundColor
        
        MDCard:
            theme_elevation_level: "Custom"
            elevation_level: 4
            elevation: 4
            theme_shadow_offset: "Custom"
            shadow_offset: 0, 0
            theme_shadow_softness: "Custom"
            shadow_softness: 4

            radius: [25] #Rounded corners
            padding: "12dp"
            size_hint: .8, .8
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            md_bg_color: app.theme_cls.backgroundColor

            MDBoxLayout:
                
                size_hint: 1, 1
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                
                padding: "16dp"
                spacing: "30dp"
                orientation: "vertical"

                MDLabel:
                    id: logintitle
                    text: "Connect to Device"
                    font_style: "Custom"
                    theme_text_color: "Custom"
                    text_color: app.theme_cls.secondaryColor
                    height: "10dp"
                    pos_hint: {"center_y": .5}
                    font_size: "100sp"
                    role: "large"


                MDTextField:
                    mode: "filled"
                    id: username
                    spacing: "10d"

                    MDTextFieldLeadingIcon:
                        icon: "account"

                    MDTextFieldHintText:
                        text: "Name"

                    MDTextFieldHelperText:
                        text: "Name of the patient"
                        mode: "persistent"

                    MDTextFieldTrailingIcon:
                        icon: "information"

                    MDTextFieldMaxLengthText:
                        max_text_length: 10

                MDTextField:
                    mode: "outlined"
                    id: ngaran

                    MDTextFieldLeadingIcon:
                        icon: "key"

                    MDTextFieldHintText:
                        text: "ID"

                    MDTextFieldHelperText:
                        text: "ID of the Product"
                        mode: "persistent"

                    MDTextFieldTrailingIcon:
                        icon: "information"

                    MDTextFieldMaxLengthText:
                        max_text_length: 10

                MDTextField:
                    mode: "outlined"
                    id:lockngaran

                    MDTextFieldLeadingIcon:
                        icon: "key"

                    MDTextFieldHintText:
                        text: "Password"

                    MDTextFieldHelperText:
                        text: "Password of the product"
                        mode: "persistent"

                    MDTextFieldTrailingIcon:
                        icon: "information"

                    MDTextFieldMaxLengthText:
                        max_text_length: 18

                MDBoxLayout:
                    size_hint: 0.9, 0.5
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    padding: "16dp"
                    orientation: "vertical"

                    MDIconButton:
                        icon: "lightbulb-outline"
                        style: "filled"
                        size_hint: None, None
                        size: "50dp", "50dp"
                        pos_hint: {"center_x": .1, "center_y": .5}
                        on_release: app.change_theme()


                    MDButton:
                        style: "tonal"
                        pos_hint: {"center_y": 0.5, "center_x": 0.9}
                        
                        on_release: app.change_screen("mainscreen")
                        on_press: app.savelogin()

                        MDButtonIcon:
                            icon: "link"

                        MDButtonText: 
                            text: "Connect"
                        
                    


    MDScreen:
        name: "mainscreen"
        

        MDBoxLayout:
            orientation: "vertical"
            md_bg_color: "#120F47"

            

            MDTopAppBar:
                type: "small"
                md_bg_color: "#18253D"

                MDTopAppBarLeadingButtonContainer:

                    MDActionTopAppBarButton:
                        icon: "pencil"
                        on_release: app.change_screen("Edit")
                        on_press: app.checkitems()


                MDTopAppBarTitle:
                    id: topbar
                    text: "SmartMed..."
                    halign: "center"
                    font_style: "Custom"
                    role: "medium"

                MDTopAppBarTrailingButtonContainer:

                    MDActionTopAppBarButton:
                        icon: "account-circle-outline"
                        on_release: app.change_screen("pic")
                        on_press: app.load_images()

                        


            MDBoxLayout:
                md_bg_color: 1, 1, 1, 1
                size_hint: 1, 0.5
                orientation: "vertical"
                md_bg_color: "#18253d"

                MDLabel:
                    id: mainname
                    text: f"Hi {app.Name}!"
                    font_style: "headingg"
                    adaptive_hight: False
                    text_color: "#FFFFFF"
                    size_hint: 1, None
                    width:
                    height: "80dp"
                    pos_hint: {"center_x": .6, "center_y": 1}
                    valign: "bottom"

                MDBoxLayout:
                    id: listcont
                    md_bg_color: "#FFFFFF"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    size_hint: 0.9, 0.9
                    elevation: 20
                    radius: [20]
                    orientation: "vertical"

                    MDBoxLayout:
                        size_hint: 0.1, 0.1
                    

                    FitImage:
                        elevation: 30
                        shadow_softness: 5
                        shadow_offset: -5, 5
                        fit_mode: "fill"
                        height: "60dp"
                        width: "50dp"
                        size_hint: 0.5, 0.7
                        source: "product.png"
                        pos_hint: {"top": .88}
                        radius: "36dp", "36dp", 0, 0
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDScrollView:
                        padding: "20dp"

                        MDList:
                            id: listahan
                            spacing: "3dp"
                            adaptive_hight: True
                            width: "100dp"
                            padding: "4dp"

                            
                
                MDBoxLayout:
                    adaptive_hight: False
                    size_hint: 0.9, None
                    height: "60dp"
                    width:
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDIconButton:
                        icon: "pencil-outline"
                        style: "standard"
                        pos_hint: {"center_y": 0.5, "center_x": 1}
                        on_release: app.change_screen("editscreen")

    MDScreen:
        name: "editscreen"

        MDBoxLayout:
            orientation: "vertical"
            md_bg_color: app.theme_cls.backgroundColor

            

            MDTopAppBar:
                type: "small"
                md_bg_color: app.theme_cls.backgroundColor

                MDTopAppBarLeadingButtonContainer:

                    MDActionTopAppBarButton:
                        icon: "arrow-left"
                        on_release: app.change_screen("mainscreen")


                MDTopAppBarTitle:
                    id: topbar
                    text: "SmartMed..."
                    halign: "center"
                    font_style: "Custom"
                    role: "medium"

                MDTopAppBarTrailingButtonContainer:

                    MDActionTopAppBarButton:
                        icon: "account-circle-outline"
                        on_release: app.change_screen("silog")

            MDBoxLayout:
                orientation: "vertical"
                md_bg_color: app.theme_cls.backgroundColor


                MDButton:
                    style: "tonal" 
                    width: 0.5
                    hight: .1
                    on_release: app.show_date_picker()
                    id: datepickerbutton

                    MDButtonText:
                        id: date
                        text: "SET DATE!"
                        font_style: "Custom"


                MDButton:
                    style: "tonal" 
                    width: 0.5
                    hight: .1
                    on_press:  app.set(1)
                    on_release: app.show_time_picker(1)
                    

                    MDButtonText:
                        id: chamber1time
                        text: "Select Time"
                        text: f"The time set is: "
                        font_style: "Custom"

                    
                
                MDBoxLayout:
                    MDBoxLayout:
                        adaptive_height: True

                        MDCheckbox:
                            id: checkcham1

                        MDLabel:
                            text: "Medicine 1"
                            adaptive_height: True
                            padding_x: "12dp"
                            pos_hint: {"center_y": .5}
                            role: "small"
                    MDBoxLayout:
                        adaptive_height: True

                        MDCheckbox:
                            id: checkcham2

                        MDLabel:
                            text: "Medicine 2"
                            adaptive_height: True
                            role: "small"
                            padding_x: "12dp"
                            pos_hint: {"center_y": .5}
                    MDBoxLayout:
                        adaptive_height: True

                        MDCheckbox:
                            id: checkcham3

                        MDLabel:
                            text: "Medicine 3"
                            adaptive_height: True
                            padding_x: "12dp"
                            role: "small"
                            pos_hint: {"center_y": .5}

                    MDBoxLayout:
                        adaptive_height: True

                        MDCheckbox:
                            id: checkdaily
                            on_active: app.disable_sched(*args)

                        MDLabel:
                            text: "Daily"
                            adaptive_height: True
                            padding_x: "12dp"
                            pos_hint: {"center_y": .5}




                MDBoxLayout:
                    size_hint: 0.9, 0.5
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    padding: "16dp"
                    orientation: "vertical"


                    MDButton:
                        style: "tonal"
                        pos_hint: {"center_y": 0.5, "center_x": 0.9}
                        
                        on_release: app.change_screen("mainscreen")
                        on_press: app.saveschedule()

                        MDButtonIcon:
                            icon: "save"

                        MDButtonText: 
                            text: "Save"


    MDScreen:
        name: "Edit"

        MDBoxLayout:
            orientation: "vertical"
            md_bg_color: app.theme_cls.backgroundColor

            

            MDTopAppBar:
                type: "small"
                md_bg_color: app.theme_cls.backgroundColor

                MDTopAppBarLeadingButtonContainer:

                    MDActionTopAppBarButton:
                        icon: "arrow-left"
                        on_release: app.change_screen("mainscreen")


                MDTopAppBarTitle:
                    id: topbar
                    text: "EDIT"
                    halign: "center"
                    font_style: "headingg"
                    role: "medium"

                        


            MDBoxLayout:
                md_bg_color: 1, 1, 1, 1
                size_hint: 1, 0.5
                orientation: "vertical"
                md_bg_color: app.theme_cls.backgroundColor


                MDBoxLayout:
                    id: listcont
                    md_bg_color: "#e3ebf7"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    size_hint: 0.9, 0.9
                    elevation: 20
                    radius: [20]
                    orientation: "vertical"
                    


                    MDScrollView:
                        padding: "20dp"

                        MDList:
                            id: listahanedit
                            spacing: "3dp"
                            adaptive_hight: True
                            width: "100dp"
                            padding: "4dp"

                            
                
                MDBoxLayout:
                    adaptive_hight: False
                    size_hint: 0.9, None
                    height: "60dp"
                    width:
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDIconButton:
                        icon: "trash-can"
                        style: "standard"
                        pos_hint: {"center_y": 0.5, "center_x": 1}
                        on_release: app.remove_schedule()

    MDScreen:
        name: "pic"
        MDBoxLayout:
            orientation: "vertical"
            md_bg_color: app.theme_cls.backgroundColor

            

            MDTopAppBar:
                type: "small"
                md_bg_color: app.theme_cls.backgroundColor

                MDTopAppBarLeadingButtonContainer:

                    MDActionTopAppBarButton:
                        icon: "arrow-left"
                        on_release: app.change_screen("mainscreen")


                MDTopAppBarTitle:
                    id: topbar
                    text: "Pictures"
                    halign: "center"
                    font_style: "headingg"
                    role: "medium"

                        


            MDBoxLayout:
                md_bg_color: 1, 1, 1, 1
                size_hint: 1, 0.5
                orientation: "vertical"
                md_bg_color: app.theme_cls.backgroundColor


                MDBoxLayout:
                    id: listcont
                    md_bg_color: app.theme_cls.primaryColor
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    size_hint: 0.9, 0.9
                    elevation: 20
                    radius: [20]
                    orientation: "vertical"

                    ScrollView:
                        MDGridLayout:
                            id: grid
                            cols: 2
                            adaptive_height: True
                            padding: dp(10)
                            spacing: dp(10)


    




<Createupdatescreen>:




<createphoto>:
    pos_hint: {"center_x": .5, "center_y": .5}
    size_hint: None, None
    size: "120dp", "120dp"
    overlap: False

    MDSmartTileImage:
        source: "bg.jpg"
        radius: [dp(24), dp(24), 0, 0]

    MDSmartTileOverlayContainer:
        md_bg_color: 0, 0, 0, .5
        adaptive_height: True
        padding: "8dp"
        spacing: "8dp"
        radius: [0, 0, dp(24), dp(24)]

        MDIconButton:
            icon: "heart-outline"
            theme_icon_color: "Custom"
            icon_color: 1, 0, 0, 1
            pos_hint: {"center_y": .5}
            on_release:
                self.icon = "heart" \
                if self.icon == "heart-outline" else \
                "heart-outline"

        MDLabel:
            text: "Ibanez GRG121DX-BKF"
            theme_text_color: "Custom"
            text_color: "white"

<item>:
    radius: "20dp", "20dp", "20dp", "20dp"
    md_bg_color: "#363633"
    adaptive_hight: False
    size_hint: 1, None
    height: "60dp"
    

    MDListItemLeadingIcon:
        icon: "bell"
        icon_color: "#1b243b"
        icon_size: "300dp"

    MDListItemTrailingIcon:











    







